// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rrzndbgeqanpgeilniqt.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJyem5kYmdlcWFucGdlaWxuaXF0Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDI1NDI1NDYsImV4cCI6MjA1ODExODU0Nn0.tu1FubvfwFiu6P71Dwn4BAK1TYcc_UCIiwSVFyPHdwE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);