// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ahnrdxuvvbjhteoxwpol.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImFobnJkeHV2dmJqaHRlb3h3cG9sIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDIzNTIwNjgsImV4cCI6MjA1NzkyODA2OH0.4YhT8qqHCZt2Zb2OCMGayfx3kHSfG5jLHSbRbrOVmSg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);